# Site settings
title: Jeffrey Borcean
email: jeffrey@borcean.xyz
description: > #
  Jeffrey is a third year computer science student at Oregon State University,
  he is also a student systems engineer with the OSU Open Source Lab.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://borcean.xyz" # the base hostname & protocol for your site

# User setting
owner: Jeffrey Borcean
email: jeffrey@borcean.xyz
facebook_username: jeffreyborcean
twitter_username: jjborcean
github_username: borcean
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone: +15038043008
copyright: Jeffrey Borcean

# Google Analytics
tracking_id: UA-72504144-1

# Build settings
markdown: kramdown
